# Generated by Django 2.2.7 on 2019-12-04 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_datetime', models.DateTimeField(default=datetime.datetime(2019, 12, 4, 3, 43, 8, 715452))),
                ('record_cpu_data', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
