# Generated by Django 2.2.7 on 2019-12-25 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_cpu_data',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 14, 51, 13, 965345)),
        ),
    ]
