# Generated by Django 2.2.7 on 2019-12-25 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_util', '0002_auto_20191225_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 28, 8, 195640)),
        ),
    ]
